-- Scope ProjectAssetPair uniqueness to each project so assets can be reused across projects.
-- Apply using: psql "$DATABASE_URL" -f backend/migrations/008_project_pair_scoped_uniques.sql

-- Drop the old global unique constraints generated by SQLAlchemy's unique=True flags.
ALTER TABLE project_asset_pairs
    DROP CONSTRAINT IF EXISTS project_asset_pairs_jpeg_asset_id_key,
    DROP CONSTRAINT IF EXISTS project_asset_pairs_raw_asset_id_key;

-- Deduplicate any rows that would violate the new per-project constraints by keeping the oldest row.
DELETE FROM project_asset_pairs pap
USING project_asset_pairs other
WHERE pap.id > other.id
  AND pap.project_id = other.project_id
  AND pap.jpeg_asset_id = other.jpeg_asset_id;

DELETE FROM project_asset_pairs pap
USING project_asset_pairs other
WHERE pap.id > other.id
  AND pap.project_id = other.project_id
  AND pap.raw_asset_id = other.raw_asset_id;

-- Add the new scoped constraints.
ALTER TABLE project_asset_pairs
    ADD CONSTRAINT uq_project_asset_pairs_project_jpeg UNIQUE (project_id, jpeg_asset_id),
    ADD CONSTRAINT uq_project_asset_pairs_project_raw UNIQUE (project_id, raw_asset_id);
